blog/urls.py
from django.urls import path
from .views import index, detail, share, subscribe, search, about

app_name = 'blog'

urlpatterns = [
    path('', index, name='index'),
    path("<int:year>/<int:month>/<int:day>/<slug:slug>/", detail, name='detail'),
    path('<int:post_id>/share/', share, name='share'),
    path('tag/<slug:tag_slug>/', index, name='posts_by_tag'),
    path('subscribe/', subscribe, name='subscribe'),
    path('search/', search, name='search'),
    path('about/', about, name='about')
    
]

mysite/urls.py
# from django.conf import settings
# import debug_toolbar

from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    # path('__debug__/', include(debug_toolbar.urls))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/partials/alerts.html
{% if messages %}

{% for message  in messages %}

<div id="message" class="container">
    <div class="alert alert-{{ message.tags }} alert-dimissible text-center" role="alert">
    <button class="close" data-dismiss="alert"> <span aria-hidden="true">&times;</span></button>
    {{ message }}
    </div>
</div>

{% endfor %}

{% endif %}

templates/partials/footer.html
<!--Footer-->
<footer class="row" id="footer">
    <div class="container">
        <div class="row top-footer">
            <div class="widget col-sm-3 widget-about">
                <div class="row m0">
                    <a href="" style="font-size: 2.5rem; color: black"> <em style="font-size: 3.2rem; color: lightgreen; padding: 1rem">Dope</em>  Blog</a>
                </div>
            </div>
            <div class="widget col-sm-5 widget-menu">
                <div class="row">
                    <ul class="nav column-menu white-bg">
                        <li><a href="{% url 'blog:index' %}">Home</a></li>
                        <li><a href="#">About</a></li>
                        <li><a href="#">categories</a></li>
                       
                    </ul>
                    <ul class="nav column-menu white-bg">
                        <li><a href="#">Search</a></li>
                        <li><a href="#">contact</a></li>
                    </ul>
                </div>
            </div>

            <!-- Subscribe-->
            <div class="widget col-sm-4 widget-subscribe">
                <h5 class="widget-title">subscribe to our newsletter.</h5>
                <form action="{% url 'blog:subscribe' %}" method="post" class="form-inline subscribe-form">
                {% csrf_token %}                  
                    <div class="form-group">
                        <input type="email" name='email' class="form-control" placeholder="Email">
                    </div>
                    <button type="submit" class="btn btn-primary btn-sm"><span>send</span></button>
                </form>
            </div>
        </div>
        <div>
            <h5 class="copyright"> All Rights Reserved - Dope Blog.
            <a class="right-side" href="#"> &copy; Copyright 2019 - 2020, Miracle</a> 
        </h5>
        </div>
    </div>
</footer>

templates/partials/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

templates/partials/navbar.html
 {% load static %}
 
 <!-- Navigation  bar-->
<header style="background-color: black" class="row transparent black header1" data-spy="affix" data-offset-top="0" id="header">
    <div class="container">
        <div class="row top-header">
            <div class="col-sm-4 search-form-col">

                <!-- Search -->
                <form action="{% url 'blog:search' %}" class="search-form">
                    <div class="input-group">
                        <span class="input-group-addon"><img src="{% static 'images/search-icon-white.png' %}" alt=""></span>
                        <input type="search" name='query' class="form-control" placeholder="search">
                    </div>
                </form>
            </div>
            <div class="col-sm-4 logo-col text-center">
                <a href="{% url 'blog:index' %}" style="font-size: 2.5rem; color: white"> <em style="font-size: 3.2rem; color: lightgreen; padding: 1rem">Dope</em>  Blog</a>
            </div>
            <div class="col-sm-4 menu-trigger-col">
                <button class="menu-trigger pull-right">
                    <span class="active-page">home</span>
                    <img src="{% static 'images/menu-align-white.png' %}" alt="" class="icon-burger">
                    <img src="{% static 'images/menu-close-white.png' %}" alt="" class="icon-cross">
                </button>
            </div>
        </div>        
    </div>
    <div class="row menu-section">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 menu-col">
                    <div class="row">
                        <ul class="nav column-menu black-bg">
                            <li {% if '/' == request.path %} class="active" {% endif %} >
                            <a href="{% url 'blog:index' %}">Home</a></li>
                            <li {% if 'post' in request.path %} class="active" {% endif %} ><a href="#">Posts</a></li>
                        </ul>
                        <ul class="nav column-menu black-bg">
                            <li {% if 'about' in request.path %} class="active" {% endif %} >
                            <a href="#">About Us</a></li>
                        </ul>
                    </div>
                </div>

                <!-- Subscribe-->
                <div class="col-sm-4 subscribe-col">
                    <h5 class="widget-title">subscribe to our newsletter.</h5>
                    <form id="nav-search" action="{% url 'blog:subscribe' %}" method="post" class="form-inline subscribe-form">                    {% csrf_token %}
                        <div class="form-group">
                            <input type="email" name="email" class="form-control" placeholder="Email">
                        </div>
                        <button type="submit" class="btn btn-primary btn-sm"><span>send</span></button>
                    </form>
                    <ul class="nav social-nav dark">
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-facebook-official"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                        <li><a href="#"><i class="fa fa-envelope"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</header>

templates/partials/paginator.html
<div class="container">
  <div class="row">
    <div class="col-md-12" style='margin-bottom: 2rem; font-size: 1.7rem'>

    <span class="step-links">
        {% if page.has_previous %}
        <a style="margin-right: 1rem; font-size: 1.7rem" href="?page={{ page.previous_page_number }}">Previous</a> 
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %} 
        <a style="margin-left: 1rem; font-size: 1.7rem" href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>


    </div>
</div>
</div>


    