blog/urls.py
from django.urls import path
from .views import index, detail, share, subscribe, search, about

app_name = 'blog'

urlpatterns = [
    path('', index, name='index'),
    path("<int:year>/<int:month>/<int:day>/<slug:slug>/", detail, name='detail'),
    path('<int:post_id>/share/', share, name='share'),
    path('tag/<slug:tag_slug>/', index, name='posts_by_tag'),
    path('subscribe/', subscribe, name='subscribe'),
    path('search/', search, name='search'),
    path('about/', about, name='about')
    
]

mysite/urls.py
# from django.conf import settings
# import debug_toolbar

from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    # path('__debug__/', include(debug_toolbar.urls))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


# class PublishedManager(models.Manager):    # creating custom manager
#     def get_queryset(self):
#         return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    # objects = models.Manager() # the default manager
    # published = PublishedManager() # custom manager
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('publish', 'Publish'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                                related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES,
                                default='draft')
    image = models.FileField(upload_to='photos', blank=True)                            

    tags = TaggableManager()                                                  

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:detail", args=[self.publish.year,
                                            self.publish.month,
                                            self.publish.day,
                                            self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                                    related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'                                                                           


class Subscribe(models.Model):
    email = models.EmailField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

    class Meta:
        verbose_name_plural = "Subscriptions"

blog/forms.py
from django import forms
from .models import Comment, Post
from ckeditor.widgets import CKEditorWidget


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25, widget=forms.TextInput(
                                    attrs={'class': 'form-control',
                                    'placeholder': 'Your name'}))
    email = forms.EmailField(widget=forms.EmailInput(
                                    attrs={'class': 'form-control',
                                    'placeholder': 'Your email address here'}))
    to = forms.EmailField(widget=forms.EmailInput(
                                    attrs={'class': 'form-control',
                                    'placeholder': "Receiver's email address"}))
    comments = forms.CharField(required=False, widget=forms.Textarea(
                                    attrs={'class': 'form-control',
                                    'placeholder': 'Write message here'}))


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

        # You either use this method or use the custom tags and filter method to specify attrs
        #  widgets = {
        #     'name': TextInput(attrs={'class': 'form-control', 'placeholder': 'Title'}),
        #     'body': Textarea(attrs={'class': 'form-control', 'placeholder': 'Text'}),
        # }
        

class PostAdminForm(forms.ModelForm):
    body = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Post
        fields = '__all__'        

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment, Subscribe
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from django.contrib import messages
# from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank


def index(request, tag_slug=None):
    object_list = Post.objects.filter(status='publish')
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 6) # 3 posts per page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an intger deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        #  if page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/index.html', {'posts': posts,
                                                'page': page, 'tag': tag})


def detail(request, year, month, day, slug):
    post = get_object_or_404(Post, slug=slug,
                                 publish__year=year,
                                 publish__month=month,
                                 publish__day=day)
    # list of active comments for this post
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            #create from object but don't save to the db
            new_comment = comment_form.save(commit=False)
            new_comment.post = post # assign current post to the comment
            new_comment.save() # save comment to db
        
            comment_form = CommentForm()
    else:
        comment_form = CommentForm()


    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)

    similar_posts = Post.objects.filter(status='publish').filter(
                                        tags__in=post_tags_ids).exclude(id=post.id)

    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by(
                                        '-same_tags','-publish')[:4]
        
    return render(request, 'blog/detail.html', {'post':post, 'comments': comments,
                                                'new_comment': new_comment, 'comment_form': comment_form,
                                                'similar_posts': similar_posts})



def share(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    sent = False

    if request.method == "POST":
        form = EmailPostForm(request.POST)

        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} ({cd['email']}) recommends you reading '{post.title}'"
            message = f"Read '{post.title}' at {post_url}\n\n{cd['name']}'s comments: {cd['comments']}"
            send_mail(subject, message, 'collinsalex50@gmail.com', [cd['to']])

            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/share.html', {'post': post,
                                                'form': form,
                                                'sent': sent})


def subscribe(request):
    if request.method == 'POST':
        sub = Subscribe(email=request.POST['email'])
        sub.save()
        messages.success(request, 'Your subscription was successfull!')
        return redirect('blog:index')


# def search(request):
#     results = []
#     query = None
    
#     if 'query' in request.GET:
#         query = request.GET['query']

#         search_vector = SearchVector('title', 'body')
#         search_query = SearchQuery(query)
#         results = Post.objects.annotate(search=search_vector, rank=SearchRank                                         (search_vector, search_query)).filter                                             (search=search_query).order_by('-rank')

#     return render(request, 'blog/search.html', {'search_value': request.GET,
#                                                 'query': query, 'results': results})


def search(request):
    results = []
    query = None
    
    if 'query' in request.GET:
        query = request.GET['query']

        results = Post.objects.filter(title__icontains=query)
    return render(request, 'blog/search.html', {'query': query,
                                            'results': results})


def about(request):
    return render(request, 'blog/about.html', {})

templates/blog/about.html
{% extends 'base.html' %}

{% block title %} About {% endblock title %}

{% block content %}

{% include 'partials/navbar.html' %}

  {% comment %} <!-- Main Content -->
  <div style="padding-top: 15rem; width: 66.66% " class="container">
    <div class="row">
        <h1 style="margin: 2rem;" class="text-center">About Me</h1>
      <
      </div>
    </div>
  </div>

  <hr> {% endcomment %}





<section class="row content-wrap">
    <div class="container" style="width: 70%">
        <div class="row">
            <div class="col-md-12 single-post-contents">

                <article class="single-post-content row m0 post">
                    <header class="row">

                        <!--Post title-->
                        <h2 class="post-title text-center"> About Me </h2>
                        
                    </header>


                        <!--Post content-->
                    <div class="post-content row">
                       
                      <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?
                      </p>
			<br>
                      <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!
                      </p>
			<br>
                      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!
                      </p>
                                      
                    </div>

                </article>

            </div>
        </div>
    </div>
</section>


  
  {% include 'partials/footer.html' %}

  {% endblock content %}

templates/blog/detail.html
{% extends "base.html" %}

{% block title %} {{ post.title }} {% endblock title %}

{% block content %}

{% load static %}       

{% load custom_tags %}

{% include 'partials/navbar.html' %}


<section class="row content-wrap">
    <div class="container">
        <div class="row">
            <div class="col-md-8 single-post-contents">
                <article class="single-post-content row m0 post">
                    <header class="row">

                         <!--Date and author-->
                        <h5 class="post-meta">
                            <a href="#" class="date">{{ post.publish }}</a>
                            <span class="post-author"><i>by</i><a href="#">
                            {{ post.author }}</a>
                            </span>
                        </h5>

                        <!--Post title-->
                        <h2 class="post-title"> {{ post.title }} </h2>

                        <!--Tags-->
                        <div class="row">
                            <h5 class="taxonomy pull-left"> <i>in</i> 
                            {% for tag in post.tags.all %}
                                <a href="{% url "blog:posts_by_tag" tag.slug %}">
                                {{ tag.name}}</a>{% if not forloop.last %},
                                {% endif %}
                            {% endfor %}
                            </h5>

                            <!--Comment count-->
                            <div class="response-count pull-right">
                            <img src="{% static 'images/comment-icon-gray.png' %}" alt="">
                            {% with comments.count as total_comment %}
                            {{ total_comment }}
                             {% endwith %}
                            </div>
                           
                        </div>
                    </header>

                    <!--Post image-->
                    {% if post.image %}
                    <div class="featured-content row m0">
                        <a href="#"><img src="{{ post.image.url }}" alt=""></a>
                    </div>
                    {% endif %}

                        <!--Post content-->
                    <div style="padding: 2.3rem; line-height: 1.8rem" class="post-content row">
                       
                        <p > {{ post.body|safe }} </p>
                        
                    </div>

                    <!--Share-->
                    <div class="row m0 tags">
                        <a href="{% url "blog:share" post.id %}" class="tag">Share this post</a>
                        
                    </div>
                    
                   
                    <!--Comment Section-->
                    <div class="row m0 comments">

                        <!--comment count-->
                        {% with comments.count as total_comments %}
                        <h5 class="response-count">{{ total_comments }} comment{{ total_comments|pluralize }}
                        <a href="#comment-form" class="btn btn-primary pull-right"><span>add comment</span></a></h5>
                        {% endwith %}

                    <!--Commenter avatar/picture-->
                    {% for comment in comments %}

                        <div class="media comment">
                            <div class="media-left">
                                <a href="#">
                                <img src="{% static 'images/avatar1.png' %}" alt="" class="img-circle"></a>
                            </div>

                            <!--comment body, date and author-->
                            <div class="media-body">
                                <h4><a href="#">{{ comment.name }}</a></h4>
                                <h5><a href="#" class="date">{{ comment.created }}</a> | <a href="#" class="reply-link">Comment 
                                {{ forloop.counter }}</a>
                                </h5>
                                <p>{{ comment.body|linebreaks }}
                                </p>
                            </div>
                        </div>

                {% empty %}

                    <h4>There are no comments yet.</h4>

                {% endfor %}

                    </div>

                    <!--Comment form-->
                    <form action="." method="post" class="comment-form row" id="comment-form">
                    {% csrf_token %}
                        <h5 class="form-title">leave a reply</h5>
                        <div class="form-group col-sm-6">
                            <label for="name">full name*</label>
                    {{ comment_form.name|add_attr:"class:form-control, placeholder:Your name,id:name" }}
                        </div>

                        <div class="form-group col-sm-6">
                            <label for="email">Email*</label>
                    {{ comment_form.email|add_attr:"class:form-control, placeholder:Your email address here,id:email" }}   
                        </div>
                        
                        <div class="form-group col-sm-12">
                            <label for="message">message</label>
                    {{ comment_form.body|add_attr:"class:form-control" }}
                        </div>
                        <div class="col-sm-12">
                            <button type="submit" class="btn-primary"><span>Add Comment</span></button>
                            <h5 class="pull-right">*required fields</h5>
                        </div>
                    </form>
                </article>
            </div>


            <!--Side bar-->
            <div class="col-md-4 sidebar"> 

                <!--Similar Posts-->
                <aside class="row m0 widget-author widget">
                    <div class="widget-author-inner row">
                        <h2 class="author-name">Similar Posts</h2>

                        {% for post in similar_posts %}
                        <ul>
                    <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
                        </ul>
                            {% empty %}
                                <p>There are no similar posts yet.</p>
                            {% endfor %}
                    </div>
                </aside>
                                
                <!--Latest Posts-->
                <aside class="row m0 widget-author widget">
                    <div class="widget-author-inner row">
                        <h2 class="author-name">Latest Posts</h2>

                        {% show_latest_posts 4 %}
                        
                    </div>
                </aside>

                    <!--Most commented Posts-->
                <aside class="row m0 widget-author widget">
                    <div class="widget-author-inner row">
                        <h3 class="author-name">Most Commented</h3>

                        {% get_most_commented_posts as most_commented_posts %}

                        <ul>
                            {% for post in most_commented_posts %}
                        <li>
                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </li>
                            {% endfor %}
                        </ul>
                    </div>
                </aside>
                
            </div>
        </div>
    </div>
</section>


{% include 'partials/footer.html' %}


{% endblock content %}

templates/blog/index.html
{% extends "base.html" %} {% load static %}

{% block title %} Welcome {% endblock %}

{% load custom_tags %}

{% block content %}

{% include 'partials/navbar.html' %}

<!-- Page body -->
<section class="row content-wrap">
    <div class="container">

    {% include 'partials/alerts.html' %}
    
            <div class="col-lg-8">

        {% if tag %}

            <h2>Posts tagged with "{{ tag.name }}"</h2>

        {% endif %}

        <div class="row" id="post-masonry">

        {% for post in posts %}
            
            <!--Blog Post-->
            <article class="col-lg-6 post post-masonry post-format-image">
                <div class="post-wrapper row">

                  <!--Post image-->
                  {% if post.image %}
                    <div class="featured-content row">
                        <a href="{{ post.get_absolute_url }}"><img src="{{ post.image.url }}" alt="" class="img-responsive">
                        </a>
                    </div>
                    {% endif %}
                    <div class="post-excerpt row">

                      <!--Author and date-->
                        <h5 class="post-meta">
                            <a href="#" class="date">{{ post.publish }}</a>
                            <span class="post-author"><i>by</i><a href="#">{{ post.author }}</a>
                            </span>
                        </h5>

                        <!--Post title and content-->
                        <h3 class="post-title"> 
                        <a href="{{ post.get_absolute_url }}"> {{ post.title }} </a>
                        </h3>
                        <p> 
                        {{ post.body|safe|truncatewords_html:20 }}
                         </p>

                        <!--Tags-->
                        <footer class="row">
                            <h5 class="taxonomy"> <i>in</i>

                            {% for tag in post.tags.all %}
                                <a href="{% url "blog:posts_by_tag" tag.slug %}">
                                {{ tag.name }}</a>{% if not forloop.last %},
                                
                                {% endif %}
                            {% endfor %}
                            </h5>

                            <!--Comment icon and count-->
                            <div class="response-count">
                            <img src="{% static 'images/comment-icon-gray.png' %}" alt="">
                            </div>
                        </footer>
                    </div>
                </div>
            </article>

        {% empty %}

            <h2>No posts yet</h2>


        {% endfor %}
           
        </div>
    </div>




    <!-- Side bar -->
<div class="col-lg-4">
    <div class="row" id="post-masonry">

        <aside class="col-lg-12 widget-author widget widget-with-posts post">
                <div class="widget-author-inner row">
                    <div class="author-avatar row">
                        {% comment %} <a href="#">
                        </a> {% endcomment %}
                        <img width='100%' height='auto' src="{% static 'images/author4.jpg' %}" alt="" class="img-circle">
                    </div>
                    <a href="#"><h2 class="author-name">Miracle Alex</h2></a>
                    <h5 class="author-title">Software Developer</h5>
                    <p>I'm a mission-driven software developer with experience in
                        enterprise and high-performance web technologies. A
                        fullstack developer but favours backend development.</p>
                    <a href="https://github.com/mirakul1" class="know-more">know more</a>
                </div>
                <ul class="nav social-nav">
                    <li><a href="https://twitter.com/iammiraclealex"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="https://linkedin.com/in/mirakul1"><i class="fa fa-linkedin"></i></a></li>
                    <li><a href="https://github.com/mirakul1"><i class="fa fa-github"></i></a></li>
                    <li><a href="https://instagram.com/mirakul_1"><i class="fa fa-instagram"></i></a></li>
                    <li><a href="mailto: collinsalex50@gmail.com"><i class="fa fa-envelope"></i></a></li>
                </ul>
            </aside>

        </div>   

            <!--Latest Posts-->
                <aside class="row m0 widget-author widget">
                    <div class="widget-author-inner row">
                        <h2 class="author-name">Latest Posts</h2>

                        {% show_latest_posts 4 %}
                        
                    </div>
                </aside>

                    <!--Most commented Posts-->
                <aside class="row m0 widget-author widget">
                    <div class="widget-author-inner row">
                        <h3 class="author-name">Most Commented</h3>

                        {% get_most_commented_posts as most_commented_posts %}

                        <ul>
                            {% for post in most_commented_posts %}
                        <li>
                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </li>
                            {% endfor %}
                        </ul>
                    </div>
                </aside>


    </div>

    </div>
    
</section>

{% include "partials/paginator.html" with page=posts %}
 







{% include 'partials/footer.html' %}

{% endblock content %}

templates/blog/search.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Search {% endblock title %}

{% block content %}

{% include 'partials/navbar.html' %} 


<!-- Page body -->
<section class="row content-wrap">
    <div class="container">
            <div class="col-lg-12">

            {% if query %}
            
            <h1>Posts containing "{{ query }}"</h1>
            <h3>
                {% with results.count as total_results %}
                Found {{ total_results }} result{{ total_results|pluralize }}
                {% endwith %}
            </h3>

        <div class="row" id="post-masonry">

        {% for post in results %}
            
            <!--Blog Post-->
            <article class="col-lg-4 post post-masonry post-format-image">
                <div class="post-wrapper row">
                    <div class="post-excerpt row">

                        <!--Post title and content-->
                        <h3 class="post-title"> 
                        <a href="{{ post.get_absolute_url }}"> {{ post.title }} </a>
                        </h3>
                        <p> {{ post.body|truncatewords:15 }} </p>

                            <!--Comment icon and count-->
                            <div class="response-count">
                            <img src="{% static 'images/comment-icon-gray.png' %}" alt="">
                            </div>
                        </footer>
                    </div>
                </div>
            </article>

        {% empty %}

            <h3>There are no results for your query.</h3>


        {% endfor %}
           
        </div>
    </div>

{% endif %}

    

    </div>
</section>



{% include 'partials/footer.html' %}

{% endblock content %}

templates/blog/share.html
{% extends "base.html" %}

{% load static %}

{% block title %} Share a post {% endblock %}

{% block content %}

{% load custom_tags %}

{% include 'partials/navbar.html' %}


<section class="row page-content-wrap">
    <div class="container">

    {% if sent %}

        <h1> E-mail Successfully Sent! </h1>
     <h4>
        "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
    </h4>

    {% else %}

        <h3 class="page-header text-center">Share "{{ post.title }}" by E-mail</h3>

        <div class="row">

            <div class="col-md-8 page-contents">
                <div class="row page-content">
                    <div class="contents row">
                        <br>

                        <!--Share form-->
                        <form action="{% url 'blog:share' post.id %}" method="post" class="contact-form row">
                                 {% csrf_token %}
                            <div class="form-group col-sm-6">
                                <label for="name">Your name*</label>
                                  {{ form.name }}
                            </div>

                            <div class="form-group col-sm-6">
                                <label for="email">Your Email*</label>
                                {{ form.email }}
                            </div>

                            <div class="form-group col-sm-6">
                                <label for="website">Receiver's Email*</label>
                                {{ form.to }}
                            </div>
                            
                            <div class="form-group col-sm-12">
                                <label for="message">message</label>
                                {{ form.comments }}
                            </div>

                            <div class="col-sm-12">
                                <button type="submit" class="btn-primary"><span>Send e-mail</span></button>
                                <h5 class="pull-right">*required fields</h5>
                            </div>
                        </form>
                       
                    </div>                    
                </div>
            </div>


            <div class="col-md-4 sidebar">              

                    <!--Latest Posts-->
                <aside class="row m0 widget-author widget">
                    <div class="widget-author-inner row">
                        <h2 class="author-name">Latest Posts</h2>

                        {% show_latest_posts 5 %}
                        
                    </div>
                </aside>

                    <!--Most commented Posts-->
                <aside class="row m0 widget-author widget">
                    <div class="widget-author-inner row">
                        <h3 class="author-name">Most Commented</h3>

                        {% get_most_commented_posts as most_commented_posts %}

                        <ul>
                            {% for post in most_commented_posts %}
                        <li>
                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </li>
                            {% endfor %}
                        </ul>
                    </div>
                </aside>
               
            </div> 
             {% endif %}

        </div>
    </div>
</section>

{% include 'partials/footer.html' %}

{% endblock content %}